extends Node

const TERRAIN_ZLAYER = 0
const GROUND_SCATTER_ZLAYER = 1
const DEFAULT_SCATTER_ZLAYER = 2
const STRUCTURE_ZLAYER = 2

const FLYING_ZLAYER = 3
const CLOUDS_ZLAYER = 5

const UNIT_MARKER_ZLAYER = 4
const HUD_ZLAYER = 6